[package]
name = "barest"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader="0.9"
x86_64="0.14"
spin = "0.9"
volatile = "0.4"

[dependencies.lazy_static]
version = "1.5.0"
default-features = false






